export const CATEGORY_FILTER_MAPPINGS: Record<string, string[]> = {
  // Stone Collection Categories
  '/collections/stone-collection/marble-tiles': ['marble-tiles'],
  '/collections/stone-collection/limestone-tiles': ['limestone-tiles'],
  '/collections/stone-collection/stone-mosaic-tiles': ['mosaic-tiles'],
  '/collections/stone-collection/travertine-tiles': ['travertine-tiles'],
  '/collections/stone-collection/slate-tiles': ['slate-tiles'],
  '/collections/stone-collection/stone-pavers': ['stone-pavers'],
  '/collections/stone-collection/granite-tiles': ['granite-tiles'],
  '/collections/stone-collection/clay-brick-slips': ['clay-brick-slips'],
  '/collections/bookmatch-slabs': ['bookmatch-slabs'],
  '/collections/slabs': ['slabs'],
  '/collections/vanity-tops': ['vanity-tops'],
  '/collections/off-cut-granite-quartz': ['off-cut-granite-quartz'],
  '/collections/custom-stonework/window-sills': ['window-sills'],
  '/collections/stone-collection/mouldings-skirtings': ['mouldings-skirtings'],
  '/collections/custom-stonework/stone-sinks': ['stone-sinks'],
  '/collections/custom-stonework/slate-hearths': ['slate-hearths'],
  '/collections/custom-stonework/table-tops': ['table-tops'],
  '/collections/design-pattern-collection/chequerboard-tiles': ['chequerboard-tiles'],
  '/collections/design-pattern-collection/herringbone-tiles': ['herringbone-tiles'],
  '/collections/design-pattern-collection/hexagon-tiles': ['hexagon-tiles'],
  '/collections/design-pattern-collection/metro-tiles': ['metro-tiles'],
  '/collections/design-pattern-collection/maxi-chequerboard-tiles': ['maxi-chequerboard-tiles'],
  '/collections/design-pattern-collection/octagon-cabochon-tiles': ['octagon-cabochon-tiles'],
  '/collections/design-pattern-collection/triangle-tiles': ['triangle-tiles'],
  '/stone-collection/stock-clearance': ['stock-clearance'],
  
  // Color Categories
  '/colour/whites': ['white', 'ivory'],
  '/colour/blacks': ['black', 'black-and-white'],
  '/colour/greys': ['grey'],
  '/colour/beiges-browns': ['beige', 'brown', 'beige-brown'],
  '/colour/creams-yellows': ['cream', 'yellow', 'cream-yellow'],
  '/colour/blues-greens': ['blue', 'green', 'blue-green'],
  '/colour/reds-pinks': ['red', 'pink', 'red-pink'],
  '/colour/multi-colour': ['multi-colour'],
  
  // Usage Area Categories
  '/room-type-usage/kitchen': ['kitchen'],
  '/room-type-usage/kitchen-splashback': ['kitchen-splashback'],
  '/room-type-usage/bathroom': ['bathroom'],
  '/room-type-usage/bathroom-floor': ['bathroom', 'bathroom-floor'],
  '/room-type-usage/living-room': ['living-room'],
  '/room-type-usage/living-room-floor': ['living-room', 'living-room-floor'],
  '/room-type-usage/outdoor': ['outdoor'],
  '/room-type-usage/pool': ['pool'],
  '/room-type-usage/wet-room': ['wet-room'],
  
  // Finish Categories
  '/finish/tumbled-rough-edgy': ['tumbled-rough-edgy'],
  '/finish/polished-shiny-smooth': ['polished-shiny-smooth'],
  '/finish/honed-matt-smooth': ['honed-matt-smooth'],
  '/finish/split-face': ['split-face'],
  '/finish/brushed-rough-finish': ['brushed-rough-finish'],
} as const;